name: counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_reload:
    path: ../

  flutter:
    sdk: flutter

  http: ^1.3.0

dev_dependencies:
  surf_lint_rules: ^3.1.0

flutter:
  uses-material-design: true
